# Grabs VS Code's devcontainer base image for Ubuntu
FROM mcr.microsoft.com/vscode/devcontainers/base:focal

# Copy library scripts to execute
COPY overlay/*.sh /tmp/overlay/

# Install necessary packages
RUN /tmp/overlay/install-packages.sh
RUN /tmp/overlay/install-python-hatch.sh